// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// characters_charactersCollection data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class characters_charactersCollection : Icharacters_charactersCollection 
    {
		private const int MaxResults = 10;
        private readonly ObservableCollection<Entities.charactersSchema> _data = new ObservableCollection<Entities.charactersSchema>
		{
          new Entities.charactersSchema
            {
                Id= new Guid("3914200f-481b-4cd5-a8e2-f75daf7c0f12"),
                Title=@"ไมโตะ ไก",
                Subtitle=@"อาจารย์นินจาของหมู่บ้านโคโนฮะ เป็นคนที่คอยฝึกสอน ร็อค ลี,ฮิวงะ เนจิ และเท็นเท็น เขาไว้ผมทรงเดียวกับ บรู๊ซ ลี ไกรักลีที่เป็นลูกศิษย์อย่างกับลูกในไส้เลยทีเดียว",
                Image=@"\Images\Item-50b93bb8-c13d-493e-82ff-4eacd3f8947c.jpg",
                Description=@"อาจารย์นินจาของหมู่บ้านโคโนฮะ เป็นคนที่คอยฝึกสอน ร็อค ลี,ฮิวงะ เนจิ และเท็นเท็น เขาไว้ผมทรงเดียวกับ บรู๊ซ ลี ไกรักลีที่เป็นลูกศิษย์อย่างกับลูกในไส้เลยทีเดียว",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("8aa70e7a-defc-496b-80d2-cb77f52f9530"),
                Title=@"จิไรยะ ",
                Subtitle=@"เป็นนินจาในตำนานที่เก่งสุดๆ",
                Image=@"\Images\Item-453e67f4-82cd-4c3c-ba12-c9b128d2d8b4.jpg",
                Description=@"ลูกศิษย์จอมโวของซารุโทบิ เป็นคนมุทะลุโผงผาง และ ทะลึ่ง แต่ก็เป็นนินจาในตำนานที่เก่งสุดๆ ขนาดลูกศิษย์เอก ยังเป็นถึงโฮคาเงะรุ่นที่ 4 เชียวนะ หลังจากโอโรจิมารุ แยกตัวออกจากโคโนะฮะ ซึนาเดะ ที่สูญเสียน้องชายและคนรักได้แยกตัวออกไป จิไรยะ ก็ใช้เวลาในการท่องเที่ยว และแต่งหนังสือนิยายรักวาบหวามเรื่อง อะจึ๊ย สวรรค์รำไร ที่ทำเอาหนุ่นๆนินจาติดกันงอมแงม โดยเฉพาะคาคาชิ ที่ต้องพกติดตัวไว้ตลอด ",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("f28d54f1-44cf-4ec5-b5c1-5ce771d6a390"),
                Title=@"ซึนาเดะ",
                Subtitle=@"โฮคาเงะของหมู่บ้านโคโนฮะ",
                Image=@"\Images\Item-7b319dfd-2093-418c-8ee8-b1ee0cb55954.jpg",
                Description=@"หลานสาวของของโฮคาเงะรุ่นที่ 1 ลูกศิษย์ของโฮคาเงะรุ่นที่ 3และเป็นหนึ่งในสามนินจาในตำนานของหมู่บ้านโคโนฮะ ซึนาเดะเป็นคนใจร้อน และเลือดร้อน ชอบท้าพนันและมักจะแพ้อยู่ทุกครั้ง ซึนาเดะมีอายุประมาณ 50 ปีแต่มีวิชานินจาที่สามารถคงความสาวสวยไว้ได้หลังจากที่ซึนะเดะสูญเสียน้องชายและแฟนในช่วงสงครามนินจา ซึนาเดะได้ชื่อว่าเป็นแพทย์นินจาที่เก่งที่สุดในดินแดนนินจา ภายหลังสงครามนินจาจบ ซึนาเดะจึงได้ออกจากหมู่บ้าน และได้ใช้เวลาของตัวเองไปกับการพนัน คู่กับชิซึเนะ",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("3cb6df17-9e4d-4d5f-b67e-a3f5bbd03842"),
                Title=@"นารา ชิกามารุ",
                Subtitle=@"นินจาจากหมู่บ้านโคโนฮะ",
                Image=@"\Images\Item-173e2b0b-ba1d-4823-9849-e9e1a06ea491.jpg",
                Description=@"มีนิสัยขี้บ่น เบื่อง่ายอยู่ตลอดเวลา และไม่ชอบผู้หญิงเป็นอย่างยิ่ง ชิกามารุมักจะโดนพ่อสอนให้เห็นความสำคัญของผู้หญิงอยู่เสมอ ",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("14e34d1f-a3d8-4b5c-8bd5-1cf15cf6f60e"),
                Title=@"ยามานากะ อิโนะ",
                Subtitle=@"นินจาแห่งหมู่บ้านโคโนฮะ",
                Image=@"\Images\Item-e7299996-1109-457e-8c84-abd007d15fc5.jpg",
                Description=@"มีความสามารถในการสิงร่างคนอื่นวิชานินจาของตระกูลยามานากะ และสามารถบังคับให้ร่างที่โดนสิงปฏิบัติตามที่ตัวเองต้องการ แต่มีข้อเสียคือเมื่อสิงร่างผู้อ่าน ร่างจริงจะไม่สามารถเคลื่อนไหวได้ซึ่งง่ายต่อการตกเป็นเป้าโจมตี และมากกว่านั้นเมื่อร่างที่เข้าไปสิงบาดเจ็บ อิโนะจะบาดเจ็บตามไปด้วย",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("913ee4f8-f858-456f-b156-ecf1f183f188"),
                Title=@"อาบุราเมะ ชิโนะ",
                Subtitle=@"นินจาจากหมู่บ้านโคโนฮะ",
                Image=@"\Images\Item-e89955dd-b9e0-4912-9dc3-7a3ed6bb65b6.jpg",
                Description=@"นินจาผู้ที่ไม่เคยเผยโฉมหน้าตนเองอีกคน (พอๆกับคาคาชิ) เป็นผู้ใช้และควบคุมแมลง โดยแมลงที่พวกเขาเลี้ยงใว้จะกินจักระของเจ้าของเป็นอาหาร เพื่อแลกเปลี่ยนกับการบังคับแมลงเพื่อใช้ในการต่อสู้ตามที่ต้องการ ในตอนสอบจูนิน อยู่ทีมเดียวกับ ฮินาตะ และ คิบะ
 ",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("748af688-e353-4779-b85d-83ac95821322"),
                Title=@"อุจิวะ ซาสึเกะ ",
                Subtitle=@"นินจาจากหมู่บ้านโคโนฮะ",
                Image=@"\Images\Item-fd853364-5b89-44e8-ae4b-2032f470027c.jpg",
                Description=@"เป็นสมาชิกคนสุดท้ายของกลุ่มอุจิวะ เป็นผู้มีความสามารถในการใช้เนตรวงแหวน โดยความสามารถนี้สามารถใช้ท่าไม้ตายของคู่ต่อสู้เพียงแค่ได้เห็นเพียงครั้งเดียว ซาสึเกะตามล้างแค้นคนที่ฆ่าล้างตระกูลเขา ซึ่งก็คือพี่ชายแท้ๆ ชื่อ อุจิวะ อิทาจิ มีนิสัยเงียบขรึม แต่ก็มีเสน่ห์ จนทำให้ ซากุระ และ อิโนะ นั้น หลงรัก",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("039cf506-587c-4a53-be50-da248f13567d"),
                Title=@"อุจิวะ อิทาจิ",
                Subtitle=@"แสงอุสา",
                Image=@"\Images\Item-b98a9dea-8666-4763-969b-cd3a541f225d.jpg",
                Description=@"พี่ชายแท้ๆของซาสึเกะ ผู้ซึ่งเป็นคนฆ่าล้างตระกูล อุจิวะ ของตนเอง จนสร้างความแค้นให้กับ ซาสึเกะ ผู้เป็นน้องชายเป็นอย่างมาก โดยอิทาจินั้นก็เป็นสมาชิกคนหนึ่งในกลุ่ม แสงอุษา",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("96ae1527-3a69-4397-9f70-d5f284359045"),
                Title=@"อุซึมากิ นารุโตะ",
                Subtitle=@"นินจาของหมู่บ้านโคโนฮะ",
                Image=@"\Images\Item-c3567dbd-381e-4dce-a29e-5309a4719961.jpg",
                Description=@"ผู้ที่ถูกผนึกจิ้งจอกเก้าหางใว้ในท้องในช่วงที่เกิดใหม่ โดยโฮคาเงะรุ่นที่ 4 ผู้สละชีวิตตัวเองต่อสู้กับปีศาจจิ้งจอกเก้าหาง นารุโตะเติบโตมากับความโดดเดี่ยวแถมถูกนินจาผู้ใหญ่ในหมู่บ้านเกลียดชัง เนื่องจากหาว่ามีจิ้งจอกเก้าหางที่เคยมาทำลายหมู่บ้านอยู่ในร่างกาย ",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("5d42e930-c616-47f3-adc2-2ce6cd13f1e5"),
                Title=@"ฮาตาเกะ คาคาชิ",
                Subtitle=@"นินจาระดับโจนินแนวหน้าของหมู่บ้านโคโนฮะ",
                Image=@"\Images\Item-991aef07-ef8e-44cf-9844-8977fcff72df.jpg",
                Description=@"มีความเป็นอิสระ เป็นตัวของตัวเองสูง ดูเหมือนเขายังมีความเจ็บปวดลึกๆ จากเรื่องในอดีต โดยปกติจะอ่านหนังสือสวรรค์รำไร (อจึ๋ยสวรรค์ ซึ่งมีอยู่ตอนนี้ในปัจจุบัน 3 ภาค คือ อจึ๋ยสวรรค์รำไร อจึ๋ยตกสววรค์ และ อจึ๋ยสวรรค์ระทม) นิยายวาบหวิวตลอดเวลา แถมผิดเวลานัดประจำ
ในอดีตนั้น เขาเคยเข้าสังกัดกองนินจาอันบุ ผมสีขาวของคาคาชิได้รับสืบทอดมาจากพ่อของเขา (ฮาตาเกะ ซาคุโมะ)พ่อของเขามีฉายาว่า""เขี้ยวสีขาวแห่งโคโนฮะ"" ซึ่งเป็นหนึ่งนินจาในตำนานของหมู่บ้านโคโนฮะ และได้รับเนตรวงแหวนซึ่งได้รับมาจาก อุจิวะ โอบิโตะ เพื่อนร่วมทีมมอบให้ก่อนที่จะเสียชีวิต โดยได้รับการผ่าตัดจากรินในระหว่างภารกิจ เป็นศิษย์ของโฮคาเงะรุ่นที่4 ที่เป็นคนผนึกจิ้งจอกเก้าหางไว้ในตัวของนารุโตะ",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("acf74d3b-1d78-4cd7-9a87-445a7be6cafc"),
                Title=@"ฮารุโนะ ซากุระ",
                Subtitle=@"นินจาแห่งหมูบ้านโคโนฮะ",
                Image=@"\Images\Item-e5510c15-2ae7-4471-8ae6-a80a0942c336.jpg",
                Description=@"เป็นคนฉลาดหลักแหลม และ ตกหลุมรักซาซึเกะอย่างมาก หลังจากที่ซากุระได้เดินทางร่วมทุกร่วมสุขกันกับกลุ่ม 7 เธอรู้สึกว่า นารุโตะ นั้นเป็นเพื่อนที่ดีมาก จากเหตุการณ์ที่ ซาซึเกะ ถอนตัวไป นารุโตะก็บาดเจ็บจากการต่อสู้ เธอ เสียใจมากที่ช่วยอะไรไม่ได้เลย ก็เลยขอเป็นลูกศิษย์ของซึนาเดะ ซึ่งเป็นนินจาแพทย์ที่เก่งที่สุดในเรื่องใช้วิชารักษาคน",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("1f242081-8c48-4fa0-a058-3fa2e5db6e22"),
                Title=@"ฮิวงะ เนจิ",
                Subtitle=@" นินจาจากหมู่บ้านโคโนฮะ",
                Image=@"\Images\Item-cb59e41d-248d-4b65-ba09-e62de6047df4.jpg",
                Description=@"ทายาทชายในตระกูลสาขาของกลุ่มฮิวงะ มีความสามารถหลักคือเนตรสีขาว ที่สามารถมองทะลุสิ่งต่างๆ และมองเห็นถึงกระแสจักระภายในร่างกายของนินจาได้ จัดเป็นอัจฉริยะของตระกูลฮิวงะ เมื่อฮิวงะ ฮินาตะ ลูกพี่ลูกน้องในตระกูลหลัก อายุได้ 3 ปี วันเดียวกับที่ ฮิวงะ เนจิ อายุ 4 ปี เนจิได้ถูกประทับอักขระ""ปักษาในกรง"" ที่หน้าผาก เพื่อเป็นสัญลักษณ์ว่าจะปกป้องตระกูลหลัก และ จุดนี่เองที่ทำให้เนจิ เกลียดฮินาตะ เพราะพ่อของเนจิ ฮิวงะ ฮิซาชิ ได้ยอมเสียชีวิตเพื่อปกป้องตระกูลฮิวงะ",
			},
          new Entities.charactersSchema
            {
                Id= new Guid("742d27bc-4ae6-435b-acea-ae5d1957a078"),
                Title=@"ฮิวงะ ฮินาตะ",
                Subtitle=@"นินจาจากหมู่บ้านโคโนฮะ",
                Image=@"\Images\Item-bb92f396-d91a-4efc-974f-b4c30cd32cb0.jpg",
                Description=@"เธอเป็นนินจาสาวที่นิสัยขี้อายมากๆ แอบชอบนารุโตะเวลาเจอหน้านารุโตะเมื่อไร เธอจะเงียบและหน้าแดงทันที เธอเป็นทายาทหญิงแห่งตระกูลหลักของกลุ่มฮิวงะ เมื่อฮินาตะอายุได้ 3 ปี วันเดียวกับที่ ฮิวงะ เนจิลูกพี่ลูกน้องจากตระกูลสาขา อายุ 4 ปี เนจิ ได้ถูกประทับอักขระ""ปักษาในกรง"" เพื่อเป็นสัญลักษณ์ว่าจะปกป้องตระกูลหลัก โดยเมื่อใดก็ตามที่ทรยศ สัญลักษณ์ปักษาในกรงจะส่งผลให้ผู้ใช้บาดเจ็บและล้มตาย ปักษาในกรงยังเป็นวิธีป้องกันความลับของเนตรสีขาว อักขระจะถูกกระตุ้นให้ทำลายความสามารถเนตรสีขาวในตัวบุคคลนั้น",
			},
		};
	
		
        /// <summary>
        /// Retrieves the data from a static data source, in an observable collection of charactersSchema items.
        /// </summary>
        /// <returns>An observable collection of charactersSchema items.</returns>
        public ObservableCollection<Entities.charactersSchema> GetData(int numPage)
        {								
			return new ObservableCollection<Entities.charactersSchema>(_data.Skip(MaxResults * numPage).Take(MaxResults));
        }
		
		/// <summary>
        /// Retrieves the data from a static data source, filtered by a filter specification, in an observable collection of charactersSchema items.
        /// </summary>
		/// <param name="filter">Filter operation specification</param>
        /// <returns>An observable collection of charactersSchema items.</returns>
        public ObservableCollection<Entities.charactersSchema> Search(FilterSpecification filter)
        {
            return RepositoriesBase.Filter<Entities.charactersSchema>.FilterCollection(filter, _data);
        }
		
		/// <summary>
        /// Checks if data source has a element before the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a previous element, false if there is not</returns>
		public bool HasPrevious(Entities.charactersSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) > 0;
        }
		
		/// <summary>
        /// Checks if data source has a element after the passed as parameter
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>True, if there is a next element, false if there is not</returns>
		public bool HasNext(Entities.charactersSchema current)
        {
            if (current == null || !_data.Any()) return false;

            return _data.IndexOf(current) < _data.Count - 1;
        }
		
		/// <summary>
        /// Retrieves the previous element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The previous element from items, if it exists. Otherwise, returns null</returns>
        public Entities.charactersSchema Previous(Entities.charactersSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.First().Equals(current)) return null;

            return _data[_data.IndexOf(current) - 1];
        }
		
		/// <summary>
        /// Retrieves the next element from source.
        /// </summary>
		/// <param name="current">Current element</param>
        /// <returns>The next element from items, if it exists. Otherwise, returns null</returns>
        public Entities.charactersSchema Next(Entities.charactersSchema current)
        {
            if (current == null || !_data.Any()) return null;

            if (_data.Last().Equals(current)) return null;

            return _data[_data.IndexOf(current) + 1];
        }
	}
}

