// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   DataSource.tt
using System;
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Globalization;
using System.Linq;
using System.Runtime.CompilerServices;
using Entities=WPAppStudio.Entities;
using RepositoriesBase=WPAppStudio.Repositories.Base;
using WPAppStudio.Shared;

namespace WPAppStudio.Repositories
{
    /// <summary>
    /// TheStoryDataSource_Html data source.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public class TheStory_TheStoryDataSource : ITheStory_TheStoryDataSource 
    {        
        /// <summary>
        /// Retrieves the html content.
        /// </summary>
        /// <returns>A string with the content in html format.</returns>
        public string Get()
        {			
            return @"<span><b>นารูโตะคือหนึ่งในการ์ตูนที่โด่งดังที่สุดของประเทศญี่ปุ่น และได้รับความนิยมประสบความสำเร็จเป็นอย่างมากในอเมริกาและยุโรป มีเนื้อหาเกี่ยวกับนินจา ศาสตร์เวทมนตร์ โดยมีกลิ่นอายความเป็นญี่ปุ่นโบราณผสมผสานกับเทคโนโลยีสมัยใหม่ได้อย่างลงตัว ปรัชญาและคำสอนที่กินใจ ปมฝั่งใจในวัยเด็กที่แตกต่างกันของแต่ละคนเชื่อมโยงสู่อตีตอย่างคาดไม่ถึง การเรียนรู้ถึงความเจ็บปวดของสงครามที่ทำให้เกิดความผิดพลาดในจิตใจของมุษย์</b></span>";
        }
	}
}

